import pandas as pd
import numpy as np
from fetch_raw_data import fetch_historical_aqi
from config import LOCATION_LATITUDE, LOCATION_LONGITUDE

def generate_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Transforms raw API data into an enriched feature set for time-series forecasting.
    """
    df = df.copy()
    
    # Sort chronologically to prevent temporal data leakage
    df = df.sort_values('time').reset_index(drop=True)
    
    # ----------------------------------------------------
    # 1. Temporal / Cyclical Features
    # ----------------------------------------------------
    df['hour'] = df['time'].dt.hour
    df['day_of_week'] = df['time'].dt.dayofweek
    df['month'] = df['time'].dt.month
    df['is_weekend'] = (df['day_of_week'] >= 5).astype(int)
    
    # ----------------------------------------------------
    # 2. Lag Features (Historical Memory)
    # ----------------------------------------------------
    # What were pollutant levels 1 hour, 3 hours, and 24 hours ago?
    for col in ['pm10', 'pm2_5', 'european_aqi']:
        df[f'{col}_lag_1h'] = df[col].shift(1)
        df[f'{col}_lag_3h'] = df[col].shift(3)
        df[f'{col}_lag_24h'] = df[col].shift(24)
        
    # ----------------------------------------------------
    # 3. Rolling Window Statistics (Trend Smoothing)
    # ----------------------------------------------------
    # Moving average over the past 6 and 24 hours
    for col in ['pm10', 'pm2_5']:
        df[f'{col}_rolling_6h_mean'] = df[col].shift(1).rolling(window=6).mean()
        df[f'{col}_rolling_24h_mean'] = df[col].shift(1).rolling(window=24).mean()
        
    # ----------------------------------------------------
    # 4. Derived Features (Pollution Velocity)
    # ----------------------------------------------------
    # AQI change rate over the last hour
    df['aqi_change_rate'] = df['european_aqi_lag_1h'] - df['european_aqi_lag_3h']
    
    # ----------------------------------------------------
    # 5. Clean NaN rows generated by shifting/rolling
    # ----------------------------------------------------
    # Shifting by 24 hours creates 24 empty rows at the beginning.
    df = df.dropna().reset_index(drop=True)
    
    return df

if __name__ == "__main__":
    print("Fetching raw dataset...")
    raw_df = fetch_historical_aqi(LOCATION_LATITUDE, LOCATION_LONGITUDE, "2024-07-01", "2026-07-21")
    
    print("Engineering features...")
    feature_df = generate_features(raw_df)
    
    print(f"\nOriginal Columns Count: {len(raw_df.columns)}")
    print(f"Engineered Columns Count: {len(feature_df.columns)}")
    print("\nNewly Generated Features Preview:")
    print(feature_df[['time', 'pm2_5', 'pm2_5_lag_1h', 'pm2_5_rolling_24h_mean', 'aqi_change_rate']].head())