from datetime import datetime, timedelta, timezone
import pandas as pd
import numpy as np
import hopsworks
try:
    from fetch_raw_data import fetch_historical_aqi
    from config import (
        LOCATION_LATITUDE, LOCATION_LONGITUDE,
        HOPSWORKS_API_KEY, HOPSWORKS_PROJECT, HOPSWORKS_HOST, HOPSWORKS_PORT
    )
except ImportError:
    from src.fetch_raw_data import fetch_historical_aqi
    from src.config import (
        LOCATION_LATITUDE, LOCATION_LONGITUDE,
        HOPSWORKS_API_KEY, HOPSWORKS_PROJECT, HOPSWORKS_HOST, HOPSWORKS_PORT
    )

def generate_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Transforms raw API data into an enriched feature set for time-series forecasting.
    """
    df = df.copy()
    
    # Sort chronologically to prevent temporal data leakage
    df = df.sort_values('time').reset_index(drop=True)
    
    # ----------------------------------------------------
    # 1. Temporal / Cyclical Features
    # ----------------------------------------------------
    df['hour'] = df['time'].dt.hour
    df['day_of_week'] = df['time'].dt.dayofweek
    df['month'] = df['time'].dt.month
    df['is_weekend'] = (df['day_of_week'] >= 5).astype(int)
    
    # Continuous trigonometric time features
    df['sin_hour'] = np.sin(2 * np.pi * df['hour'] / 24.0)
    df['cos_hour'] = np.cos(2 * np.pi * df['hour'] / 24.0)
    df['sin_day_of_week'] = np.sin(2 * np.pi * df['day_of_week'] / 7.0)
    df['cos_day_of_week'] = np.cos(2 * np.pi * df['day_of_week'] / 7.0)
    
    # ----------------------------------------------------
    # 2. Lag Features (Historical Memory)
    # ----------------------------------------------------
    df['pm2_5_lag_2h'] = df['pm2_5'].shift(2)
    df['pm2_5_lag_6h'] = df['pm2_5'].shift(6)
    df['pm2_5_lag_12h'] = df['pm2_5'].shift(12)

    for col in ['pm10', 'pm2_5', 'european_aqi']:
        df[f'{col}_lag_1h'] = df[col].shift(1)
        df[f'{col}_lag_3h'] = df[col].shift(3)
        df[f'{col}_lag_24h'] = df[col].shift(24)
        
    # ----------------------------------------------------
    # 3. Rolling Window Statistics (Trend Smoothing)
    # ----------------------------------------------------
    df['pm2_5_rolling_24h_std'] = df['pm2_5'].shift(1).rolling(window=24).std().fillna(0.0)

    for col in ['pm10', 'pm2_5']:
        df[f'{col}_rolling_6h_mean'] = df[col].shift(1).rolling(window=6).mean()
        df[f'{col}_rolling_24h_mean'] = df[col].shift(1).rolling(window=24).mean()
        
    # ----------------------------------------------------
    # 4. Derived Features (Pollution Velocity)
    # ----------------------------------------------------
    df['aqi_change_rate'] = df['european_aqi_lag_1h'] - df['european_aqi_lag_3h']
    
    # ----------------------------------------------------
    # 5. Clean NaN rows generated by shifting/rolling
    # ----------------------------------------------------
    df = df.dropna().reset_index(drop=True)
    
    return df

def run_feature_pipeline():
    print("Fetching raw dataset for recent window (14 days) to update Feature Store...")
    
    # Fetch recent historical window (14 days) to calculate lag & rolling features efficiently
    today_utc = datetime.now(timezone.utc)
    today_str = today_utc.strftime("%Y-%m-%d")
    start_str = (today_utc - timedelta(days=14)).strftime("%Y-%m-%d")
    
    raw_df = fetch_historical_aqi(LOCATION_LATITUDE, LOCATION_LONGITUDE, start_str, today_str)
    
    print("Engineering features...")
    feature_df = generate_features(raw_df)
    if feature_df.empty:
        raise ValueError("Engineered feature set is empty after lag computation. Insufficient historical rows fetched.")
    feature_df["time"] = pd.to_datetime(feature_df["time"])

    print(f"Latest engineered feature timestamp: {feature_df['time'].max()}")

    print("\nConnecting to Hopsworks Feature Store...")
    project = hopsworks.login(
        project=HOPSWORKS_PROJECT,
        host=HOPSWORKS_HOST,
        port=HOPSWORKS_PORT,
        api_key_value=HOPSWORKS_API_KEY
    )
    fs = project.get_feature_store()
    
    print("Uploading Feature Group v2 to Cloud Feature Store...")
    aqi_fg = fs.get_or_create_feature_group(
        name="aqi_hourly_features",
        version=2,
        primary_key=["time"],
        event_time="time",
        online_enabled=True,
        description="Hourly engineered air quality, meteorological and cyclical time features"
    )
    
    # Sync schema for any new engineered features
    existing_feat_names = [f.name for f in aqi_fg.features]
    new_features = []
    from hsfs.feature import Feature
    for col in feature_df.columns:
        if col not in existing_feat_names:
            dtype = "double" if feature_df[col].dtype in ['float64', 'float32', 'float'] else "bigint"
            new_features.append(Feature(col, dtype))
    if new_features:
        print(f"Schema Migration: Appending new feature(s) to Hopsworks Feature Group: {[f.name for f in new_features]}...")
        try:
            aqi_fg.append_features(new_features)
        except Exception as e:
            print(f"Note on append_features: {e}")

    print("Persisting fresh data batch to Hopsworks...")
    aqi_fg.insert(feature_df, storage="online", wait=True)
        
    print("\n✅ Successfully persisted live fresh features to Hopsworks Feature Store!")

if __name__ == "__main__":
    run_feature_pipeline()