from datetime import datetime, timedelta
import pandas as pd
import numpy as np
import hopsworks
from fetch_raw_data import fetch_historical_aqi
from config import LOCATION_LATITUDE, LOCATION_LONGITUDE

def generate_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Transforms raw API data into an enriched feature set for time-series forecasting.
    """
    df = df.copy()
    
    # Sort chronologically to prevent temporal data leakage
    df = df.sort_values('time').reset_index(drop=True)
    
    # ----------------------------------------------------
    # 1. Temporal / Cyclical Features
    # ----------------------------------------------------
    df['hour'] = df['time'].dt.hour
    df['day_of_week'] = df['time'].dt.dayofweek
    df['month'] = df['time'].dt.month
    df['is_weekend'] = (df['day_of_week'] >= 5).astype(int)
    
    # ----------------------------------------------------
    # 2. Lag Features (Historical Memory)
    # ----------------------------------------------------
    for col in ['pm10', 'pm2_5', 'european_aqi']:
        df[f'{col}_lag_1h'] = df[col].shift(1)
        df[f'{col}_lag_3h'] = df[col].shift(3)
        df[f'{col}_lag_24h'] = df[col].shift(24)
        
    # ----------------------------------------------------
    # 3. Rolling Window Statistics (Trend Smoothing)
    # ----------------------------------------------------
    for col in ['pm10', 'pm2_5']:
        df[f'{col}_rolling_6h_mean'] = df[col].shift(1).rolling(window=6).mean()
        df[f'{col}_rolling_24h_mean'] = df[col].shift(1).rolling(window=24).mean()
        
    # ----------------------------------------------------
    # 4. Derived Features (Pollution Velocity)
    # ----------------------------------------------------
    df['aqi_change_rate'] = df['european_aqi_lag_1h'] - df['european_aqi_lag_3h']
    
    # ----------------------------------------------------
    # 5. Clean NaN rows generated by shifting/rolling
    # ----------------------------------------------------
    df = df.dropna().reset_index(drop=True)
    
    return df

def run_feature_pipeline():
    print("Fetching raw dataset dynamically up to today...")
    
    # Calculate dynamic dates for ongoing ingestion
    today_str = datetime.now().strftime("%Y-%m-%d")
    start_str = (datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d")
    
    raw_df = fetch_historical_aqi(LOCATION_LATITUDE, LOCATION_LONGITUDE, start_str, today_str)
    
    print("Engineering features...")
    feature_df = generate_features(raw_df)
    feature_df["time"] = pd.to_datetime(feature_df["time"])

    print("\nConnecting to Hopsworks Feature Store...")
    project = hopsworks.login(
        project="MA",
        host="eu-west.cloud.hopsworks.ai",
        port=443,
        api_key_value="yC0HPp2g2yuZjpXH.9FmXmXktv80uISKXoBZtImHRILwMNxReE2JhWfWX2oVkBVrBJt4JPV7OQGAbMuDu"  # Kept as is
    )
    fs = project.get_feature_store()
    
    print("Uploading Feature Group to Cloud Feature Store...")
    aqi_fg = fs.get_or_create_feature_group(
        name="aqi_hourly_features",
        version=1,
        primary_key=["time"],
        event_time="time",
        online_enabled=True,
        description="Hourly engineered air quality and pollutant features"
    )
    
    print("Persisting data to Hopsworks...")
    aqi_fg.insert(feature_df, storage="online", wait=True)
        
    print("\n✅ Successfully persisted live features to Hopsworks Feature Store!")

if __name__ == "__main__":
    run_feature_pipeline()