import os
import re
import hopsworks
import pandas as pd
import numpy as np
import xgboost as xgb
import lightgbm as lgb
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import Ridge
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import joblib

try:
    from config import HOPSWORKS_API_KEY, HOPSWORKS_PROJECT, HOPSWORKS_HOST, HOPSWORKS_PORT
    from utils import convert_pm25_to_aqi
except ImportError:
    from src.config import HOPSWORKS_API_KEY, HOPSWORKS_PROJECT, HOPSWORKS_HOST, HOPSWORKS_PORT
    from src.utils import convert_pm25_to_aqi

def eval_metrics(y_true, y_pred):
    y_t = np.array(y_true, dtype=np.float64)
    y_p = np.array(y_pred, dtype=np.float64)
    mse = float(mean_squared_error(y_t, y_p))
    mae = float(mean_absolute_error(y_t, y_p))
    r2  = float(r2_score(y_t, y_p))
    return {
        "rmse": float(np.sqrt(mse)),
        "mae": float(mae),
        "r2": float(round(r2, 4))
    }

def train_evaluate_and_register_best_model():
    """
    Trains 3 Direct Multi-Horizon Models (one independent model per forecast day),
    evaluates performance on chronological splits against a naive persistence baseline,
    selects winning candidate models for each horizon, and registers the direct multi-model bundle to Hopsworks.
    """
    # ----------------------------------------------------
    # 1. Connect & Retrieve Data from Feature Store
    # ----------------------------------------------------
    print("Connecting to Hopsworks Feature Store...")
    project = hopsworks.login(
        project=HOPSWORKS_PROJECT,
        host=HOPSWORKS_HOST,
        port=HOPSWORKS_PORT,
        api_key_value=HOPSWORKS_API_KEY
    )
    fs = project.get_feature_store()
    
    try:
        fgs = fs.get_feature_groups("aqi_hourly_features")
        fg_version = max([int(fg.version) for fg in fgs]) if fgs else 2
    except Exception:
        fg_version = 2
    print(f"Reading dataset from Online Storage (Feature Group v{fg_version})...")
    aqi_fg = fs.get_feature_group(name="aqi_hourly_features", version=fg_version)
    df = aqi_fg.read(online=True)
    df = df.sort_values("time").reset_index(drop=True)

    # ----------------------------------------------------
    # 2. Direct Multi-Horizon Target Creation
    # ----------------------------------------------------
    print("\n--- Constructing 3 Direct Multi-Horizon Target Arrays ---")
    df['target_24h'] = df['pm2_5'].shift(-24)
    df['target_48h'] = df['pm2_5'].shift(-48)
    df['target_72h'] = df['pm2_5'].shift(-72)

    # Drop trailing NaN rows generated by shifts
    df = df.dropna(subset=['target_24h', 'target_48h', 'target_72h']).reset_index(drop=True)
    print(f"Dataset shape after direct horizon target alignment: {df.shape}")

    target_cols = ['pm2_5', 'target_24h', 'target_48h', 'target_72h']
    drop_cols = target_cols + (['time'] if 'time' in df.columns else [])
    feature_cols = [col for col in df.columns if col not in drop_cols]
    
    print(f"Feature set count: {len(feature_cols)} features (strictly measured at t <= 0, leak-free).")

    # Chronological 80/20 train/test split
    split_idx = int(len(df) * 0.8)
    train_df = df.iloc[:split_idx].copy()
    test_df = df.iloc[split_idx:].copy()

    X_train = train_df[feature_cols]
    X_test  = test_df[feature_cols]

    y_24h_train = train_df['target_24h']
    y_24h_test  = test_df['target_24h']

    y_48h_train = train_df['target_48h']
    y_48h_test  = test_df['target_48h']

    y_72h_train = train_df['target_72h']
    y_72h_test  = test_df['target_72h']

    # Current PM2.5 baseline for naive persistence
    y_0_test = test_df['pm2_5']

    # ----------------------------------------------------
    # 3. Naive Persistence Baseline Evaluation (y_hat_{t+H} = y_t)
    # ----------------------------------------------------
    print("\n--- Evaluating Naive Persistence Baseline (y_hat_{t+H} = y_t) ---")
    p_d1_m = eval_metrics(y_24h_test, y_0_test)
    p_d2_m = eval_metrics(y_48h_test, y_0_test)
    p_d3_m = eval_metrics(y_72h_test, y_0_test)

    persistence_rmse = (p_d1_m["rmse"] + p_d2_m["rmse"] + p_d3_m["rmse"]) / 3.0
    persistence_mae  = (p_d1_m["mae"]  + p_d2_m["mae"]  + p_d3_m["mae"])  / 3.0
    persistence_r2   = (p_d1_m["r2"]   + p_d2_m["r2"]   + p_d3_m["r2"])   / 3.0

    print(f"  Day 1 Persistence (24h) -> RMSE: {p_d1_m['rmse']:.4f} | MAE: {p_d1_m['mae']:.4f} | R2: {p_d1_m['r2']:.4f}")
    print(f"  Day 2 Persistence (48h) -> RMSE: {p_d2_m['rmse']:.4f} | MAE: {p_d2_m['mae']:.4f} | R2: {p_d2_m['r2']:.4f}")
    print(f"  Day 3 Persistence (72h) -> RMSE: {p_d3_m['rmse']:.4f} | MAE: {p_d3_m['mae']:.4f} | R2: {p_d3_m['r2']:.4f}")
    print(f"  └─ Persistence Overall  -> RMSE: {persistence_rmse:.4f} | MAE: {persistence_mae:.4f} | R2: {persistence_r2:.4f}")

    # ----------------------------------------------------
    # 4. Candidate Model Tournament Pool (including Ridge)
    # ----------------------------------------------------
    def get_candidate_pool():
        return {
            "XGBoost": xgb.XGBRegressor(n_estimators=150, learning_rate=0.05, max_depth=5, random_state=42),
            "LightGBM": lgb.LGBMRegressor(n_estimators=150, learning_rate=0.05, max_depth=5, random_state=42, verbose=-1),
            "RandomForest": RandomForestRegressor(n_estimators=100, max_depth=8, random_state=42),
            "Ridge": make_pipeline(SimpleImputer(strategy="median"), Ridge(alpha=1.0))
        }

    # --- Day 1 (24h) Tournament ---
    print("\n--- Day 1 (24h) Direct Model Tournament ---")
    d1_candidates = get_candidate_pool()
    d1_results = {}
    for name, model in d1_candidates.items():
        model.fit(X_train, y_24h_train)
        preds = model.predict(X_test)
        d1_results[name] = {"model": model, "metrics": eval_metrics(y_24h_test, preds)}
        print(f"  {name:12s} -> RMSE: {d1_results[name]['metrics']['rmse']:.4f} | MAE: {d1_results[name]['metrics']['mae']:.4f} | R2: {d1_results[name]['metrics']['r2']:.4f}")
    
    winner_d1_name = min(d1_results, key=lambda k: d1_results[k]["metrics"]["rmse"])
    model_day1 = d1_results[winner_d1_name]["model"]
    d1_m = d1_results[winner_d1_name]["metrics"]
    print(f"🏆 Day 1 Winner: {winner_d1_name} (RMSE: {d1_m['rmse']:.4f})")

    # --- Day 2 (48h) Tournament ---
    print("\n--- Day 2 (48h) Direct Model Tournament ---")
    d2_candidates = get_candidate_pool()
    d2_results = {}
    for name, model in d2_candidates.items():
        model.fit(X_train, y_48h_train)
        preds = model.predict(X_test)
        d2_results[name] = {"model": model, "metrics": eval_metrics(y_48h_test, preds)}
        print(f"  {name:12s} -> RMSE: {d2_results[name]['metrics']['rmse']:.4f} | MAE: {d2_results[name]['metrics']['mae']:.4f} | R2: {d2_results[name]['metrics']['r2']:.4f}")

    winner_d2_name = min(d2_results, key=lambda k: d2_results[k]["metrics"]["rmse"])
    model_day2 = d2_results[winner_d2_name]["model"]
    d2_m = d2_results[winner_d2_name]["metrics"]
    print(f"🏆 Day 2 Winner: {winner_d2_name} (RMSE: {d2_m['rmse']:.4f})")

    # --- Day 3 (72h) Tournament ---
    print("\n--- Day 3 (72h) Direct Model Tournament ---")
    d3_candidates = get_candidate_pool()
    d3_results = {}
    for name, model in d3_candidates.items():
        model.fit(X_train, y_72h_train)
        preds = model.predict(X_test)
        d3_results[name] = {"model": model, "metrics": eval_metrics(y_72h_test, preds)}
        print(f"  {name:12s} -> RMSE: {d3_results[name]['metrics']['rmse']:.4f} | MAE: {d3_results[name]['metrics']['mae']:.4f} | R2: {d3_results[name]['metrics']['r2']:.4f}")

    winner_d3_name = min(d3_results, key=lambda k: d3_results[k]["metrics"]["rmse"])
    model_day3 = d3_results[winner_d3_name]["model"]
    d3_m = d3_results[winner_d3_name]["metrics"]
    print(f"🏆 Day 3 Winner: {winner_d3_name} (RMSE: {d3_m['rmse']:.4f})")

    # ----------------------------------------------------
    # 5. Overall Direct Multi-Horizon Metrics & Packaging
    # ----------------------------------------------------
    overall_rmse = float(np.mean([d1_m['rmse'], d2_m['rmse'], d3_m['rmse']]))
    overall_mae  = float(np.mean([d1_m['mae'], d2_m['mae'], d3_m['mae']]))
    overall_r2   = float(np.mean([d1_m['r2'], d2_m['r2'], d3_m['r2']]))

    # Mathematical percentage lift calculation against Naive Persistence:
    # lift_pct = ((persistence_rmse - model_rmse) / persistence_rmse) * 100
    d1_lift_rmse_pct = float(round(((p_d1_m["rmse"] - d1_m["rmse"]) / p_d1_m["rmse"]) * 100.0, 2))
    d2_lift_rmse_pct = float(round(((p_d2_m["rmse"] - d2_m["rmse"]) / p_d2_m["rmse"]) * 100.0, 2))
    d3_lift_rmse_pct = float(round(((p_d3_m["rmse"] - d3_m["rmse"]) / p_d3_m["rmse"]) * 100.0, 2))
    overall_lift_rmse_pct = float(round(((persistence_rmse - overall_rmse) / persistence_rmse) * 100.0, 2))

    print("\n--- Final Direct Multi-Horizon Summary ---")
    print(f"  Day 1 (24h) [{winner_d1_name:10s}] -> RMSE: {d1_m['rmse']:.4f} | MAE: {d1_m['mae']:.4f} | R2: {d1_m['r2']:.4f} | Persistence Lift: +{d1_lift_rmse_pct:.2f}%")
    print(f"  Day 2 (48h) [{winner_d2_name:10s}] -> RMSE: {d2_m['rmse']:.4f} | MAE: {d2_m['mae']:.4f} | R2: {d2_m['r2']:.4f} | Persistence Lift: +{d2_lift_rmse_pct:.2f}%")
    print(f"  Day 3 (72h) [{winner_d3_name:10s}] -> RMSE: {d3_m['rmse']:.4f} | MAE: {d3_m['mae']:.4f} | R2: {d3_m['r2']:.4f} | Persistence Lift: +{d3_lift_rmse_pct:.2f}%")
    print(f"  Overall 72H Direct Average -> RMSE: {overall_rmse:.4f} | MAE: {overall_mae:.4f} | R2: {overall_r2:.4f} | Overall Lift: +{overall_lift_rmse_pct:.2f}%")

    # Hopsworks metadata ONLY allows numbers (floats/ints) - no strings!
    best_metrics = {
        "rmse": overall_rmse,
        "mae":  overall_mae,
        "r2":   overall_r2,
        "day1_rmse": float(d1_m["rmse"]), "day1_mae": float(d1_m["mae"]), "day1_r2": float(d1_m["r2"]),
        "day2_rmse": float(d2_m["rmse"]), "day2_mae": float(d2_m["mae"]), "day2_r2": float(d2_m["r2"]),
        "day3_rmse": float(d3_m["rmse"]), "day3_mae": float(d3_m["mae"]), "day3_r2": float(d3_m["r2"]),
        "day1_lift_rmse_pct": d1_lift_rmse_pct,
        "day2_lift_rmse_pct": d2_lift_rmse_pct,
        "day3_lift_rmse_pct": d3_lift_rmse_pct,
        "overall_lift_rmse_pct": overall_lift_rmse_pct,
        "overall_72h_rmse": overall_rmse,
        "overall_72h_mae":  overall_mae,
        "overall_72h_r2":   overall_r2,
        "persistence_rmse": float(persistence_rmse),
        "persistence_mae":  float(persistence_mae),
        "persistence_r2":   float(persistence_r2)
    }

    # ----------------------------------------------------
    # 6. Model Promotion Gate, SHAP Explainability & Registry Serving
    # ----------------------------------------------------
    print("\n--- Computing SHAP Global Feature Importance ---")
    def compute_shap_feature_importance(model, X_df, feature_cols):
        try:
            import shap
            explainer = shap.TreeExplainer(model)
            shap_values = explainer.shap_values(X_df)
            if isinstance(shap_values, list):
                shap_values = shap_values[0]
            mean_abs_shap = np.abs(shap_values).mean(axis=0)
            importance_dict = dict(zip(feature_cols, mean_abs_shap.tolist()))
            sorted_imp = sorted(importance_dict.items(), key=lambda x: x[1], reverse=True)
            return [{"feature": feat, "importance": round(float(val), 4)} for feat, val in sorted_imp]
        except Exception as e:
            print(f"SHAP TreeExplainer note: {e}. Using model feature_importances_ fallback.")
            if hasattr(model, "feature_importances_"):
                imp = model.feature_importances_
                sorted_imp = sorted(zip(feature_cols, imp), key=lambda x: x[1], reverse=True)
                return [{"feature": feat, "importance": round(float(val), 4)} for feat, val in sorted_imp]
            return []

    shap_importance_24h = compute_shap_feature_importance(model_day1, X_train, feature_cols)
    print(f"Top 5 SHAP Features (Day 1 Model): {shap_importance_24h[:5]}")

    print("\n--- Automated Model Promotion Gate ---")
    mr = project.get_model_registry()
    
    # Save multi-model bundle to local directory
    model_dir = "aqi_best_model"
    os.makedirs(model_dir, exist_ok=True)
    
    multi_model_bundle = {
        "model_24h": model_day1,
        "model_48h": model_day2,
        "model_72h": model_day3,
        "feature_cols": feature_cols,
        "day1_winner": winner_d1_name,
        "day2_winner": winner_d2_name,
        "day3_winner": winner_d3_name,
        "shap_importance_24h": shap_importance_24h
    }
    
    joblib.dump(multi_model_bundle, os.path.join(model_dir, "model.pkl"))
    print("Successfully packaged 3 Direct Models + SHAP Feature Importance into model.pkl artifact.")

    # ----------------------------------------------------
    # Model Promotion Gate Implementation
    # ----------------------------------------------------
    reg_name = "aqi_pm25_predictor"
    candidate_rmse = overall_rmse
    should_promote = True

    try:
        existing_models = mr.get_models(reg_name)
        if existing_models:
            # Retrieve latest active version from Hopsworks Model Registry
            latest_model = max(existing_models, key=lambda m: getattr(m, "version", 0))
            metrics_dict = getattr(latest_model, "training_metrics", {}) or {}
            active_rmse_val = metrics_dict.get("rmse")
            if active_rmse_val is not None:
                active_rmse = float(active_rmse_val)
                if candidate_rmse >= active_rmse:
                    should_promote = False
                    print(f"[PROMOTION GATE] REJECTED: Candidate model (RMSE: {candidate_rmse:.4f}) did not beat active model (RMSE: {active_rmse:.4f}). Active version retained.")
                else:
                    print(f"[PROMOTION GATE] PASSED: New model beats active production model (Candidate RMSE: {candidate_rmse:.4f} < Active RMSE: {active_rmse:.4f}). Promoting version.")
            else:
                print(f"[PROMOTION GATE] PASSED: Existing model version exists but lacks recorded RMSE metric. Promoting version (Candidate RMSE: {candidate_rmse:.4f}).")
        else:
            print(f"[PROMOTION GATE] PASSED: No previous model versions exist in registry. Promoting initial version (Candidate RMSE: {candidate_rmse:.4f}).")
    except Exception as e:
        print(f"[PROMOTION GATE] PASSED: Registry query note ({e}). Promoting candidate version (Candidate RMSE: {candidate_rmse:.4f}).")

    if not should_promote:
        return

    print(f"Uploading promoted 3 Direct Models bundle to Hopsworks Model Registry ('{reg_name}')...")
    hopsworks_model = mr.python.create_model(
        name=reg_name,
        metrics=best_metrics,
        description=f"Promoted 3 Direct Models Architecture (24h={winner_d1_name}, 48h={winner_d2_name}, 72h={winner_d3_name})"
    )
    hopsworks_model.save(model_dir)
    print(f"✅ Successfully registered winning Direct Model bundle to Hopsworks Model Registry ('{reg_name}')!")

if __name__ == "__main__":
    print("Starting Direct Multi-Horizon 3-Model Tournament Pipeline...")
    train_evaluate_and_register_best_model()